// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAAASUnlk3b1not2JHnw2rXPznB_WWb0Y',
    appId: '1:693325795054:web:b2534760d46b745cba2dff',
    messagingSenderId: '693325795054',
    projectId: 'flutterproject-5b971',
    authDomain: 'flutterproject-5b971.firebaseapp.com',
    storageBucket: 'flutterproject-5b971.appspot.com',
    measurementId: 'G-R3Z21W3944',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI4lSUf9jrSF_kaUupmDlYoLo5vxHpG34',
    appId: '1:693325795054:android:fbb923afd7f3c1cfba2dff',
    messagingSenderId: '693325795054',
    projectId: 'flutterproject-5b971',
    storageBucket: 'flutterproject-5b971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxMlKMLsrAhDOKlK6REBhNW4QtUxomydk',
    appId: '1:693325795054:ios:b6639b6bf49bd2f9ba2dff',
    messagingSenderId: '693325795054',
    projectId: 'flutterproject-5b971',
    storageBucket: 'flutterproject-5b971.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxMlKMLsrAhDOKlK6REBhNW4QtUxomydk',
    appId: '1:693325795054:ios:53e7494c502511e3ba2dff',
    messagingSenderId: '693325795054',
    projectId: 'flutterproject-5b971',
    storageBucket: 'flutterproject-5b971.appspot.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
